version: '3'

services:
  glossgen:
    build:
      context: ./glossgen
    env_file:
      - .env
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./glossgen/src:/app/src
    restart: unless-stopped 